name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Setup DotNet Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0"

      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: cd node && npm install

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build

      - name: Setup Nuget
        if: github.event_name == 'push'
        uses: NuGet/setup-nuget@v1

      - name: Publish
        if: matrix.os == 'windows-latest'
        run: dotnet publish -c Release --no-build

      - name: Pack
        if: matrix.os == 'windows-latest'
        run: nuget pack

      - name: Upload
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: nuget-package
          path: CssBuilder.*.nupkg
